-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 19:04:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema data_vault
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema data_vault
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data_vault` DEFAULT CHARACTER SET utf8 ;
USE `data_vault` ;

-- -----------------------------------------------------
-- Table `data_vault`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Users` (
  `UserID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Student` (
  `StudentID` VARCHAR(45) NOT NULL,
  `GroupID` INT(11) NULL,
  `UserID` INT(11) NOT NULL,
  INDEX `fk_Students_Users_idx` (`UserID` ASC) VISIBLE,
  PRIMARY KEY (`StudentID`, `UserID`),
  CONSTRAINT `fk_Students_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `data_vault`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Users-Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Users-Group` (
  `UserID` INT(11) NOT NULL,
  `GroupID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_User-Group_User1_idx` (`UserID` ASC) VISIBLE,
  INDEX `index` (`GroupID` ASC) VISIBLE,
  CONSTRAINT `fk_User-Group_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `data_vault`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Group` (
  `GroupID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  PRIMARY KEY (`GroupID`),
  CONSTRAINT `fk_Group_User-Group1`
    FOREIGN KEY (`GroupID`)
    REFERENCES `data_vault`.`Users-Group` (`GroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Group-Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Group-Assignment` (
  `GroupID` INT(11) NOT NULL,
  `AssignmentID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Group-Assignment_Group1_idx` (`GroupID` ASC) VISIBLE,
  INDEX `Assigment-iD` (`AssignmentID` ASC) VISIBLE,
  CONSTRAINT `fk_Group-Assignment_Group1`
    FOREIGN KEY (`GroupID`)
    REFERENCES `data_vault`.`Group` (`GroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Assignment` (
  `AssignmentID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Assignment_Group-Assignment1_idx` (`AssignmentID` ASC) VISIBLE,
  PRIMARY KEY (`AssignmentID`),
  CONSTRAINT `fk_Assignment_Group-Assignment1`
    FOREIGN KEY (`AssignmentID`)
    REFERENCES `data_vault`.`Group-Assignment` (`AssignmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Assignment-Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Assignment-Tasks` (
  `AssignmentID` INT(11) NOT NULL,
  `TaskID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Assignment-Task_Assignment1_idx` (`AssignmentID` ASC) VISIBLE,
  INDEX `Index_assignment_task` (`TaskID` ASC) VISIBLE,
  CONSTRAINT `fk_Assignment-Task_Assignment1`
    FOREIGN KEY (`AssignmentID`)
    REFERENCES `data_vault`.`Assignment` (`AssignmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`sat_Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`sat_Tasks` (
  `LoadDateTimeStamp` DATETIME NOT NULL,
  `TaskID` INT(11) NOT NULL,
  `RecordSource` TEXT NULL,
  `Description` LONGTEXT NULL,
  PRIMARY KEY (`LoadDateTimeStamp`, `TaskID`),
  INDEX `index_task` (`TaskID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Tasks` (
  `TaskID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  PRIMARY KEY (`TaskID`),
  CONSTRAINT `fk_Task_Assignment-Task1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `data_vault`.`Assignment-Tasks` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tasks_sat_Tasks1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `data_vault`.`sat_Tasks` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Users-Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Users-Students` (
  `UserID` INT(11) NOT NULL,
  `StudentID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_User-Students_User1_idx` (`UserID` ASC) VISIBLE,
  INDEX `users_students_index` (`StudentID` ASC) VISIBLE,
  CONSTRAINT `fk_User-Students_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `data_vault`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Students-Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Students-Group` (
  `StudentID` INT(11) NOT NULL,
  `GroupID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Students-Group_Group1_idx` (`GroupID` ASC) VISIBLE,
  INDEX `student_group_index` (`StudentID` ASC) VISIBLE,
  CONSTRAINT `fk_Students-Group_Group1`
    FOREIGN KEY (`GroupID`)
    REFERENCES `data_vault`.`Group` (`GroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Students` (
  `StudentID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Students1_User-Students1_idx` (`StudentID` ASC) VISIBLE,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `fk_Students1_User-Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `data_vault`.`Users-Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Students-Group1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `data_vault`.`Students-Group` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Students-Submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Students-Submissions` (
  `StudentID` INT(11) NOT NULL,
  `SubmissionID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Students-Submissions_Students1_idx` (`StudentID` ASC) VISIBLE,
  INDEX `students_submitions_index` (`SubmissionID` ASC) VISIBLE,
  CONSTRAINT `fk_Students-Submissions_Students1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `data_vault`.`Students` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`sat_Submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`sat_Submissions` (
  `LoadDateTimeStamp` DATETIME NOT NULL,
  `SubmissionID` INT(11) NOT NULL,
  `RecordSource` TEXT NULL,
  `Date` DATETIME NULL,
  `Content` LONGTEXT NULL,
  PRIMARY KEY (`LoadDateTimeStamp`, `SubmissionID`),
  INDEX `submissionid_index` (`SubmissionID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Submissions` (
  `SubmissionID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Submissions_Students-Submissions1_idx` (`SubmissionID` ASC) VISIBLE,
  PRIMARY KEY (`SubmissionID`),
  CONSTRAINT `fk_Submissions_Students-Submissions1`
    FOREIGN KEY (`SubmissionID`)
    REFERENCES `data_vault`.`Students-Submissions` (`SubmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Submissions_sat_Submissions1`
    FOREIGN KEY (`SubmissionID`)
    REFERENCES `data_vault`.`sat_Submissions` (`SubmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Users-Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Users-Teachers` (
  `UserID` INT(11) NOT NULL,
  `TeacherID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_User-Teachers_User1_idx` (`UserID` ASC) VISIBLE,
  INDEX `teacher_id` (`TeacherID` ASC) VISIBLE,
  CONSTRAINT `fk_User-Teachers_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `data_vault`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Teachers-Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Teachers-Group` (
  `GroupID` INT(11) NOT NULL,
  `TeacherID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Teachers-Group_Group1_idx` (`GroupID` ASC) VISIBLE,
  INDEX `Indez` (`TeacherID` ASC) VISIBLE,
  CONSTRAINT `fk_Teachers-Group_Group1`
    FOREIGN KEY (`GroupID`)
    REFERENCES `data_vault`.`Group` (`GroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Teachers` (
  `TeacherID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Teachers_User-Teachers1_idx` (`TeacherID` ASC) VISIBLE,
  PRIMARY KEY (`TeacherID`),
  CONSTRAINT `fk_Teachers_User-Teachers1`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `data_vault`.`Users-Teachers` (`TeacherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teachers_Teachers-Group1`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `data_vault`.`Teachers-Group` (`TeacherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Teachers-Supervisors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Teachers-Supervisors` (
  `TeacherID` INT(11) NOT NULL,
  `SupervisorID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Teachers-Supervisors_Teachers1_idx` (`TeacherID` ASC) VISIBLE,
  INDEX `index_teachers_supervisors` (`SupervisorID` ASC) VISIBLE,
  CONSTRAINT `fk_Teachers-Supervisors_Teachers1`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `data_vault`.`Teachers` (`TeacherID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Submissions-Supervisors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Submissions-Supervisors` (
  `SubmissionID` INT(11) NOT NULL,
  `SupervisorID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Submissions-Supervisors_Submissions1_idx` (`SupervisorID` ASC) VISIBLE,
  INDEX `submissions_supervisors_index` (`SubmissionID` ASC) VISIBLE,
  CONSTRAINT `fk_Submissions-Supervisors_Submissions1`
    FOREIGN KEY (`SupervisorID`)
    REFERENCES `data_vault`.`Submissions` (`SubmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Supervisors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Supervisors` (
  `SupervisorID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  PRIMARY KEY (`SupervisorID`),
  CONSTRAINT `fk_Supervisors_Teachers-Supervisors1`
    FOREIGN KEY (`SupervisorID`)
    REFERENCES `data_vault`.`Teachers-Supervisors` (`SupervisorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supervisors_Submissions-Supervisors1`
    FOREIGN KEY (`SupervisorID`)
    REFERENCES `data_vault`.`Submissions-Supervisors` (`SupervisorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Supervisors-Grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Supervisors-Grades` (
  `SupervisorID` INT(11) NOT NULL,
  `GradesID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Supervisor-Grades_Supervisors1_idx` (`SupervisorID` ASC) VISIBLE,
  INDEX `index_supervisor_grades` (`GradesID` ASC) VISIBLE,
  CONSTRAINT `fk_Supervisor-Grades_Supervisors1`
    FOREIGN KEY (`SupervisorID`)
    REFERENCES `data_vault`.`Supervisors` (`SupervisorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Grades` (
  `GradesID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Grades_Supervisors-Grades1_idx` (`GradesID` ASC) VISIBLE,
  PRIMARY KEY (`GradesID`),
  CONSTRAINT `fk_Grades_Supervisors-Grades1`
    FOREIGN KEY (`GradesID`)
    REFERENCES `data_vault`.`Supervisors-Grades` (`GradesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Supervisors-SupervisorsComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Supervisors-SupervisorsComments` (
  `SupervisorID` INT(11) NOT NULL,
  `CommentID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Supervisors-SupervisorComment_Supervisors1_idx` (`SupervisorID` ASC) VISIBLE,
  INDEX `index_comment_id` (`CommentID` ASC) VISIBLE,
  CONSTRAINT `fk_Supervisors-SupervisorComment_Supervisors1`
    FOREIGN KEY (`SupervisorID`)
    REFERENCES `data_vault`.`Supervisors` (`SupervisorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`SupervisorsComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`SupervisorsComments` (
  `CommentID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  PRIMARY KEY (`CommentID`),
  CONSTRAINT `fk_SupervisorComment_Supervisors-SupervisorComment1`
    FOREIGN KEY (`CommentID`)
    REFERENCES `data_vault`.`Supervisors-SupervisorsComments` (`CommentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Submissions-StudentsComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Submissions-StudentsComments` (
  `SubmissionID` INT(11) NOT NULL,
  `CommentID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Submissions-Comments_Submissions1_idx` (`SubmissionID` ASC) VISIBLE,
  INDEX `index_submussion_commets` (`CommentID` ASC) VISIBLE,
  CONSTRAINT `fk_Submissions-Comments_Submissions1`
    FOREIGN KEY (`SubmissionID`)
    REFERENCES `data_vault`.`Submissions` (`SubmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`sat_StudentsComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`sat_StudentsComments` (
  `LoadDateTimeStamp` DATETIME NOT NULL,
  `CommentID` INT(11) NOT NULL,
  `RecordSource` TEXT NULL,
  `Comment` LONGTEXT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`LoadDateTimeStamp`, `CommentID`),
  INDEX `index_commentid` (`CommentID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`StudentsComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`StudentsComments` (
  `CommentID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_StudentComment_Submissions-Comments1_idx` (`CommentID` ASC) VISIBLE,
  PRIMARY KEY (`CommentID`),
  CONSTRAINT `fk_StudentComment_Submissions-Comments1`
    FOREIGN KEY (`CommentID`)
    REFERENCES `data_vault`.`Submissions-StudentsComments` (`CommentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentsComments_sat_StudentsComments1`
    FOREIGN KEY (`CommentID`)
    REFERENCES `data_vault`.`sat_StudentsComments` (`CommentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`sat_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`sat_Users` (
  `LoadDateTimeStamp` DATETIME NOT NULL,
  `UserID` INT(11) NOT NULL,
  `RecordSource` TEXT NULL,
  `FullName` TEXT NULL,
  `UserStatus` TINYINT(1) NULL,
  `e-mail` TEXT NULL,
  PRIMARY KEY (`LoadDateTimeStamp`, `UserID`),
  INDEX `fk_sat_Users_User1_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_sat_Users_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `data_vault`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`sat_Assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`sat_Assignment` (
  `LoadDateTimeStamp` DATETIME NOT NULL,
  `AssignmentID` INT(11) NOT NULL,
  `RecordSource` TEXT NULL,
  `Description` LONGTEXT NULL,
  `DueDate` DATETIME NULL,
  PRIMARY KEY (`LoadDateTimeStamp`, `AssignmentID`),
  INDEX `fk_sat_Assignment_Assignment1_idx` (`AssignmentID` ASC) VISIBLE,
  CONSTRAINT `fk_sat_Assignment_Assignment1`
    FOREIGN KEY (`AssignmentID`)
    REFERENCES `data_vault`.`Assignment` (`AssignmentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`sat_Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`sat_Group` (
  `LoadDateTimeStamp` DATETIME NOT NULL,
  `GroupID` INT(11) NOT NULL,
  `RecordSource` TEXT NULL,
  `GroupName` TEXT NULL,
  PRIMARY KEY (`LoadDateTimeStamp`, `GroupID`),
  INDEX `fk_sat_Group_Group1_idx` (`GroupID` ASC) VISIBLE,
  CONSTRAINT `fk_sat_Group_Group1`
    FOREIGN KEY (`GroupID`)
    REFERENCES `data_vault`.`Group` (`GroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`sat_Grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`sat_Grades` (
  `LoadDateTimeStamp` DATETIME NOT NULL,
  `GradesID` INT(11) NOT NULL,
  `RecordSource` TEXT NULL,
  `Grade` INT(11) NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`LoadDateTimeStamp`, `GradesID`),
  INDEX `fk_sat_Grades_Grades1_idx` (`GradesID` ASC) VISIBLE,
  CONSTRAINT `fk_sat_Grades_Grades1`
    FOREIGN KEY (`GradesID`)
    REFERENCES `data_vault`.`Grades` (`GradesID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`sat_SupervisorsComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`sat_SupervisorsComments` (
  `LoadDateTimeStamp` DATETIME NOT NULL,
  `CommentID` INT(11) NOT NULL,
  `RecordSource` TEXT NULL,
  `Comment` LONGTEXT NULL,
  `Date` DATETIME NULL,
  PRIMARY KEY (`LoadDateTimeStamp`, `CommentID`),
  INDEX `fk_sat_SupervisorComment_SupervisorComment1_idx` (`CommentID` ASC) VISIBLE,
  CONSTRAINT `fk_sat_SupervisorComment_SupervisorComment1`
    FOREIGN KEY (`CommentID`)
    REFERENCES `data_vault`.`SupervisorsComments` (`CommentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_vault`.`Tasks-Submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_vault`.`Tasks-Submissions` (
  `SubmissionID` INT(11) NOT NULL,
  `TaskID` INT(11) NOT NULL,
  `LoadDateTimeStamp` DATETIME NULL,
  `RecordSource` TEXT NULL,
  INDEX `fk_Task-Submissions_Submissions1_idx` (`SubmissionID` ASC) VISIBLE,
  INDEX `fk_Task-Submissions_Task1_idx` (`TaskID` ASC) VISIBLE,
  CONSTRAINT `fk_Task-Submissions_Submissions1`
    FOREIGN KEY (`SubmissionID`)
    REFERENCES `data_vault`.`Submissions` (`SubmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task-Submissions_Task1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `data_vault`.`Tasks` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
